name: Dante

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Signalling Server
    env:
      PORT: 1080

    steps:
    - uses: actions/checkout@v4
    
    - name: Install ngrok
      run: |
        curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok

    - name: Run ngrok tunnel
      run: |
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ngrok tcp --url=tcp://${{ vars.NGROK_STATIC_DOMAIN }}:443 ${PORT} &

    - name: Install dante-server
      run: |
        sudo apt update -y
        sudo apt install --no-install-recommends -y dante-server

    - name: Run proxy
      run: |
        sudo echo << EOF > danted.conf
        logoutput: syslog
        user.privileged: root
        user.unprivileged: nobody

        # The listening network interface or address.
        internal: 0.0.0.0 port=${PORT}

        # The proxying network interface or address.
        external: eth0

        # socks-rules determine what is proxied through the external interface.
        socksmethod: username

        # client-rules determine who can connect to the internal interface.
        clientmethod: none

        client pass {
            from: 0.0.0.0/0 to: 0.0.0.0/0
        }

        socks pass {
            from: 0.0.0.0/0 to: 0.0.0.0/0
        }
        EOF
        sudo mv danted.conf /etc/danted.conf
        sudo systemctl restart danted
        sudo ufw allow ${PORT}/tcp
        sudo ufw reload
        sudo useradd -r -s /bin/false ${{ vars.PROXY_USER }}
        echo "${{ secrets.PROXY_PASS }}" | sudo passwd ${{ vars.PROXY_USER }}
