name: Dante

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Signalling Server
    env:
      PORT: 1080

    steps:
    - uses: actions/checkout@v4
    
    - name: Install ngrok
      run: |
        curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok

    - name: Install xray
      run: |
        sudo bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
        cat << EOF > xray.json
        {
          "log": {
            "logLevel": "debug"
          },
          "inbounds": [
            {
              "port": ${PORT},
              "protocol": "trojan",
              "settings": {
                "users": [
                  {
                    "email": "iloveass@example.com",
                    "password": "${{ secrets.PROXY_PASS }}",
                    "level": 0
                  }
                ]
              },
              "streamSettings": {
                "network": "websocket",
                "wsSettings": {
                  "acceptProxyProtocol": false,
                  "path": "/",
                  "heartbeatPeriod": 10
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom"
            }
          ]
        }
        EOF
        echo --------
        cat xray.json
        echo --------
        sudo mv xray.json /usr/local/etc/xray/config.json
        sudo systemctl enable --now xray
        sudo systemctl restart xray
        sudo systemctl status xray

    - name: Run ngrok tunnel
      run: |
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ngrok http --url=${{ vars.NGROK_STATIC_DOMAIN }} ${PORT} &
        sudo journalctl -fu xray
